name: Unit tests

on: [ push ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      - name: "Setup Node.js"
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - name: "Install Dependencies"
        id: install
        run: cd contracts && npm ci
      - name: "Backend Unit tests"
        run: |
          cd contracts && npm run test
